==== *Partie 1.2: Les interfaces graphiques pour git*
* *Qu’est-ce que le logiciel gitk ? Comment se lance-t-il ?* +
`gitk` est un logiciel qui affiche l'historique des *commits* d'un dépôt Git. Il affiche les branches, les tags, et les modifications dans une vue arborescentefootnote:[https://git-scm.com/docs/gitk[Git - gitk Documentation]]. Il se lance en exécutant la commande suivante dans un terminal, depuis le répertoire d’un dépôt Git :

[source, bash]
----
gitk
----

* *Qu’est-ce que le logiciel git-gui ? Comment se lance-t-il ?* +
`git-gui` est une interface graphique permettant de préparer des commits, gérer les index, faire des push, pull et mergefootnote:[https://git-scm.com/docs/git-gui[Git - git-gui Documentation]]. Il se lance en exécutant la commande suivante dans un terminal, toujours dans le répertoire d’un dépôt Git :

[source, bash]
----
git gui
----

==== *Partie 1.3: Installons autre chose et comparons*
* *Pourquoi avez-vous choisi ce logiciel ?* +
https://git-cola.github.io/[*Git Cola*] est un bon choix, car il est léger, open source, propose une interface claire pour gérer les dépôts Git et me rend nostalgique du _Coca Cola_.

* *Comment l’avez vous installé ?* +
Je l’ai installé en suivant les instructions de la page de téléchargement de https://git-cola.github.io/downloads.html[Git Cola] puis en exécutant la commande suivante :

[source, bash]
----
sudo apt install git-cola
----

* *Comparer-le aux outils inclus avec git ainsi qu’avec ce qui serait fait en ligne de commande pure : fonctionnalités avantages, inconvénients…*
** *Gitk* :
*** Avantages : Simple, rapide, montre un bon historique visuel.
*** Inconvénients : Interface un peu vieillotte, manque de fonctionnalités avancées.

** *Git-Gui* :
*** Avantages : Bonne gestion des index, possibilité de commit visuellement.
*** Inconvénients : Interface minimaliste, pas très intuitive pour les débutants.

** *Git-Cola* :
*** Avantages : Interface moderne, nombreuses fonctionnalités, personnalisable.
*** Inconvénients : Peut être plus lourd et complexe à prendre en main.

** *Ligne de commande Git* :
*** Avantages : Puissante, flexible, tout est accessible via des commandes.
*** Inconvénients : Courbe d’apprentissage plus élevée, nécessite de mémoriser des commandes.