= Rapport SAE 2.03 ISR
:toc: left
:icons: font
:lang: fr
:encoding: UTF-8
:doctype: article
:figure-caption!:
:pdf-fontsdir: font
:pdf-themesdir: theme
:toc-title: Table des matières

[abstract]
.Résumé
Ce rapport documente les étapes et apprentissages réalisés durant la SAE2.03 ISR. + 
Il est structuré en plusieurs semaines de travail. La première concerne l’installation et la configuration de Debian, avec la mise en place d’une machine virtuelle et l’automatisation de son installation. Ensuite, l’apprentissage du balisage léger qui n'est pas rédigée. La troisième semaine est dédiée à la recherche et à l’étude des applications clientes Git, comparant différentes interfaces comme *GitK*, *Git-Gui* et *Git Cola*. Enfin, la dernière semaine traite de l’installation et de l’utilisation de *Gitea*, un service d’hébergement Git, en expliquant son installation, ses paramétrages et sa configuration en tant que service.

<<<

== Semaine 1: Installation et Configuration de Debian.

[NOTE]
====
Durant la première semaine de la SAE, l'installation de la machine virtuelle ainsi qu'une grande partie des tâches demandées ont été réalisées sous Windows. Nous avons procédé légèrement différemment, mais nous avons tout de même compris le concept.
====

=== 1.1: Réponses aux questions.
include::src/semaine 1/questions.adoc[]

=== 1.2: Rapport sur nos actions réalisées durant cette semaine.

[NOTE]
====
Concernant le rapport de nos actions sur la *partie 2 à 4*, nous n’avons pas jugé pertinent de le détailler, car nous nous sommes simplement conformés aux exigences demandées.
====

include::src/semaine 1/rapport.adoc[]

=== 1.3: Procédure pour l'Auto-Installation de Debian
Cette section vous guidera dans l'installation automatique de Debian sur Windows, ainsi que sur Linux et d'autres systèmes _(où vous devez adapter la méthode)_.

include::src/semaine 1/procedure.adoc[]

<<<

== Semaine 2: Apprentissage Balisage Léger - Base

<<<

== Semaine 3: Recherche et étude des applications clientes.
=== 3.1: Réponses aux questions.

include::src/semaine 3/questions.adoc[]

=== 3.2: Rapport sur nos actions réalisées durant cette semaine.

include::src/semaine 3/rapport.adoc[]

<<<

== Semaine 4: Gitea : Installation & Utilisation du Service
=== 4.1: Réponses aux questions.

include::src/semaine 4/questions.adoc[]

=== 4.2: Rapport sur nos actions réalisées durant cette semaine.

[NOTE]
====
Le rapport sera structuré en deux parties : 

* *link:#installation_gitea[L'installation de Gitea]* où je décris le processus d'installation de Gitea, les erreurs rencontrées et les solutions que j'ai appliquées pour les corriger.

* *link:#utilisation_gitea[L'utilisation de Gitea]* où j'explique mon utilisation de Gitea.
====

include::src/semaine 4/rapport-installation.adoc[]

include::src/semaine 4/rapport-utilisation.adoc[]

=== 4.3: Procédure pour l'installation de Gitea

[NOTE]
====
Cette section vous guidera à travers les étapes nécessaires pour installer *Gitea version 1.23.5* et le configurer en tant que service sur une machine Linux.
====

include::src/semaine 4/procedure.adoc[]