<<<<<<< HEAD
= SAE 2.03 ISR - README

== Liste des membres de l'équipe
* POZZO Kilian : kilian.pozzo.etu@univ-lille.fr
* NKANZA Benn : benn.nkanza.etu@univ-lille.fr
* VEROULIDZE Anri : anri.veroulidze.etu@univ-lille.fr
* NOURDINE El-Khair : el-khair.nourdine.etu@univ-lille.fr

== Prérequis
====
*Ruby*: AsciiDoc nécessite `Ruby` pour être exécuté. Assurez-vous d'avoir Ruby installé sur votre système. 

Vous pouvez vérifier si Ruby est installé en ouvrant l'invite de commande (cmd) et en exécutant la commande : 

[source, bash]
----
ruby -v
---- 
Si Ruby n'est pas installé, vous pouvez télécharger la dernière version de Ruby en cliquant ici: https://rubyinstaller.org/downloads/[Ruby Installer for Windows]

*Gems* : AsciiDoc est disponible en tant que `gem` Ruby. Assurez-vous que vous avez RubyGems installé pour pouvoir installer les gems.
====

== Installation

[STEP]
====
*Installer AsciiDoc via RubyGems*

* Ouvrez une invite de commande (cmd) ou PowerShell en tant qu'administrateur.
* Installez le gem AsciiDoc en exécutant la commande suivante : 

[source, bash]
----
gem install asciidoctor
---- 

* Une fois l'installation terminée, vous pouvez vérifier qu'AsciiDoc est correctement installé en exécutant :

[source, bash]
----
asciidoctor -v
----
====

== Utilisation AsciiDoctor
[STEP]
====
Pour convertir un fichier AsciiDoc (.adoc) en HTML, utilisez la commande suivante :

[source, bash]
----
asciidoctor votre_fichier.adoc
----
====

== Prérequis supplémentaires pour la conversion en PDF
Si vous souhaitez convertir des fichiers AsciiDoc en PDF, vous devez installer quelques outils supplémentaires.

[STEP]
====
* Installer asciidoctor-pdf 

[source, bash]
----
gem install asciidoctor-pdf
----

* Utilisation AsciiDoctor-PDF

[source, bash]
----
asciidoctor-pdf votre_fichier.adoc
----
====

== Ressources et liens utiles
* https://rubyinstaller.org/downloads/[Ruby Installer for Windows]
* https://docs.asciidoctor.org/asciidoc/latest/[Documentation Officielle AsciiDoc]
=======
= SAE 2.03 ISR - README

== Liste des membres de l'équipe
* POZZO Kilian : kilian.pozzo.etu@univ-lille.fr
* NKANZA Benn : benn.nkanza.etu@univ-lille.fr
* VEROULIDZE Anri : anri.veroulidze.etu@univ-lille.fr
* NOURDINE El-Khair : el-khair.nourdine.etu@univ-lille.fr

== Prérequis
====
*Ruby*: AsciiDoctor nécessite `Ruby` pour être exécuté. Assurez-vous d'avoir *Ruby* installé sur votre système. 

Vous pouvez vérifier si Ruby est installé en ouvrant l'invite de commande _(cmd)_ et en exécutant la commande : 

[source, bash]
----
ruby -v
----

Si Ruby n'est pas installé, vous pouvez télécharger la dernière version de Ruby en cliquant ici: https://rubyinstaller.org/downloads/[Ruby Installer for Windows]

*Gems* : AsciiDoctor est disponible en tant que `gem` *Ruby* _(framework pour Ruby)_. +
Assurez-vous que vous avez https://rubygems.org/[RubyGems] installé pour pouvoir installer AsciiDoctor.
====

== Installation

====
*Installer AsciiDoctor via RubyGems*

* Ouvrez une invite de commande _(cmd)_ ou PowerShell en tant qu'administrateur.
* Installez le gem AsciiDoctor en exécutant la commande suivante : 

[source, bash]
----
gem install asciidoctor
----

* Une fois l'installation terminée, vous pouvez vérifier qu'AsciiDoctor est correctement installé en exécutant :

[source, bash]
----
asciidoctor -v
----
====

== Utilisation AsciiDoctor

====
Pour convertir le rapport AsciiDoc _(.adoc)_ en HTML _(.html)_, utilisez la commande suivante :

[source, bash]
----
asciidoctor rapport.adoc
----
====

== Prérequis supplémentaires pour la conversion en PDF
Si vous souhaitez convertir le rapport AsciiDoc _(.adoc)_ en PDF _(.pdf)_, vous devez installer quelques outils supplémentaires.

====
* *Installer `asciidoctor-pdf`*

[source, bash]
----
gem install asciidoctor-pdf
----

* *Utilisation AsciiDoctor-PDF*

[source, bash]
----
asciidoctor-pdf -a pdf-theme=my-theme.yml rapport.adoc
----
====

== Ressources et liens utiles
* https://rubyinstaller.org/downloads/[Ruby Installer for Windows]
* https://docs.asciidoctor.org/asciidoc/latest/[Documentation Officielle AsciiDoc]
* https://docs.asciidoctor.org/asciidoctor/latest/[Documentation Officielle AsciiDoctor]
>>>>>>> 4ac2910 (rapport-final)
